import { z } from 'zod';

/**
 * Shared contracts between the mobile app and the API.
 * Keeping DTOs and schemas here prevents client/server drift.
 */

// --- Restaurant day (shared time semantics) ---

/**
 * Fixed timezone that defines the restaurant's business day. Both the client and
 * the server derive "today" from this zone so reservations and check-in always
 * agree on the current day, regardless of the device or server process timezone
 * (e.g. an API container running in UTC).
 */
export const RESTAURANT_TIME_ZONE = 'America/Bogota';

/**
 * Returns the YYYY-MM-DD calendar date for the given instant in the restaurant's
 * timezone. The en-CA locale always formats as YYYY-MM-DD.
 */
export function restaurantDateISO(instant: Date = new Date()): string {
  return new Intl.DateTimeFormat('en-CA', {
    timeZone: RESTAURANT_TIME_ZONE,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(instant);
}

// --- Auth (Feature 01) ---

export const requestOtpSchema = z.object({
  email: z.string().email(),
});
export type RequestOtpDto = z.infer<typeof requestOtpSchema>;

export const verifyOtpSchema = z.object({
  email: z.string().email(),
  code: z.string().length(6),
});
export type VerifyOtpDto = z.infer<typeof verifyOtpSchema>;

export interface AuthTokens {
  accessToken: string;
  refreshToken: string;
}

export const refreshTokenSchema = z.object({
  refreshToken: z.string().min(1),
});
export type RefreshTokenDto = z.infer<typeof refreshTokenSchema>;

// --- User (Feature 01 / 04 / 05) ---

export type UserRole = 'guest' | 'qa' | 'admin';

export interface User {
  id: string;
  email: string;
  name: string | null;
  role: UserRole;
}

export interface AuthResponse extends AuthTokens {
  user: User;
}

// --- Reservations (Feature 01) ---

export type ReservationStatus = 'pending' | 'confirmed' | 'completed' | 'no_show';

// Max active (pending + confirmed) reservations a user can hold at once.
export const MAX_ACTIVE_RESERVATIONS = 2;

export const createReservationSchema = z.object({
  date: z.string(), // ISO date (YYYY-MM-DD)
  time: z.string(), // HH:mm
  partySize: z.number().int().positive(),
});
export type CreateReservationDto = z.infer<typeof createReservationSchema>;

// Editing a reservation reuses the same shape as creation.
export const updateReservationSchema = createReservationSchema;
export type UpdateReservationDto = z.infer<typeof updateReservationSchema>;

export interface Reservation {
  id: string;
  date: string;
  time: string;
  partySize: number;
  status: ReservationStatus;
}

// --- Check-in & devices (Feature 03) ---

export const checkinSchema = z.object({
  qrToken: z.string().min(1),
});
export type CheckinDto = z.infer<typeof checkinSchema>;

export const registerDeviceSchema = z.object({
  expoPushToken: z.string().min(1),
  platform: z.enum(['ios', 'android']),
});
export type RegisterDeviceDto = z.infer<typeof registerDeviceSchema>;

export interface CheckinResponse {
  reservationId: string;
  checkedInAt: string; // ISO timestamp
  welcomeMessage: string; // Spanish welcome message shown after check-in
  alreadyCheckedIn: boolean;
}

// Current check-in state for the authenticated user (Feature 05 gating).
export interface CheckinStatusResponse {
  checkedIn: boolean;
  checkedInAt: string | null; // ISO timestamp when checkedIn is true
}

// Entrance code shown/generated by QA (Feature 05). The QR encodes `code`.
// It rotates weekly or when an admin regenerates it.
export interface EntranceCodeResponse {
  code: string; // 4-digit entrance code
  updatedAt: string; // ISO timestamp of the last rotation
}

// --- Itinerary (Feature 02) ---

export interface ItineraryMilestone {
  id: string;
  order: number;
  time: string; // HH:mm
  name: string;
  description: string;
  x: number; // normalized 0..1 position on the venue map
  y: number; // normalized 0..1 position on the venue map
}

export interface ItineraryResponse {
  reservationId: string | null;
  milestones: ItineraryMilestone[];
}

// --- Content: Menu, Garden, Guide (Feature 04) ---
// Client-owned static content for the MVP (no CMS). Typed here so screens render
// from a stable contract and the source can later move to an API without changes.
// `imageUrl` accepts a remote URL (e.g. an uploaded image) or a bundled asset URI.

export interface MenuItem {
  id: string;
  name: string; // Spanish, customer-facing
  description: string; // Spanish, customer-facing
  imageUrl?: string;
  tags?: string[]; // Spanish labels, e.g. "vegano", "de la huerta"
  order: number;
}

export interface MenuSection {
  id: string;
  title: string; // Spanish section name, e.g. "Entradas"
  items: MenuItem[];
  order: number;
}

export interface GardenSection {
  id: string;
  title: string; // Spanish, e.g. "La huerta", "Riego", "Compostaje"
  body: string; // Spanish paragraph(s)
  imageUrl?: string;
  order: number;
}

// A predefined question/answer pair for the guide chatbot (no AI in this phase).
export interface GuideQuestion {
  id: string;
  question: string; // Spanish, shown as a suggested prompt
  answer: string; // Spanish, predefined reply
}

// --- Content administration DTOs (Feature 06) ---
// Admin-only write payloads. Read shapes reuse MenuSection/MenuItem/GardenSection.

export const menuSectionCreateSchema = z.object({
  title: z.string().min(1),
  order: z.number().int().nonnegative().optional(),
});
export type MenuSectionCreateDto = z.infer<typeof menuSectionCreateSchema>;
export const menuSectionUpdateSchema = menuSectionCreateSchema.partial();
export type MenuSectionUpdateDto = z.infer<typeof menuSectionUpdateSchema>;

export const menuItemCreateSchema = z.object({
  sectionId: z.string().min(1),
  name: z.string().min(1),
  description: z.string().min(1),
  imageUrl: z.string().url().optional(),
  tags: z.array(z.string()).optional(),
  order: z.number().int().nonnegative().optional(),
});
export type MenuItemCreateDto = z.infer<typeof menuItemCreateSchema>;
export const menuItemUpdateSchema = menuItemCreateSchema.omit({ sectionId: true }).partial();
export type MenuItemUpdateDto = z.infer<typeof menuItemUpdateSchema>;

export const gardenSectionCreateSchema = z.object({
  title: z.string().min(1),
  body: z.string().min(1),
  imageUrl: z.string().url().optional(),
  order: z.number().int().nonnegative().optional(),
});
export type GardenSectionCreateDto = z.infer<typeof gardenSectionCreateSchema>;
export const gardenSectionUpdateSchema = gardenSectionCreateSchema.partial();
export type GardenSectionUpdateDto = z.infer<typeof gardenSectionUpdateSchema>;

export const guideQuestionCreateSchema = z.object({
  question: z.string().min(1),
  answer: z.string().min(1),
  order: z.number().int().nonnegative().optional(),
});
export type GuideQuestionCreateDto = z.infer<typeof guideQuestionCreateSchema>;
export const guideQuestionUpdateSchema = guideQuestionCreateSchema.partial();
export type GuideQuestionUpdateDto = z.infer<typeof guideQuestionUpdateSchema>;

// Response after uploading a content image.
export interface ImageUploadResponse {
  url: string;
}
